/**
 * HPM3 Hoops starter drill library — v1, written by Jennifer for Coach to edit.
 * 6 levels × Handle / Finish / Shoot, plus Activate and Engine (no levels).
 * Every hoop drill has a no-hoop variant so a driveway or hallway still gets a full session.
 * Coach: edit names/cues/minutes in /coach/drills and paste demo video links. Marked isSample until you touch them.
 */
import type { Block } from "../src/db/schema";

export type D = { block: Block; level: number; name: string; description: string; needsHoop?: boolean; noHoopName?: string; noHoopDescription?: string; minutes: number };

export const DRILLS: D[] = [
  // ───────── ACTIVATE (every session, no levels) ─────────
  { block: "ACTIVATE", level: 1, name: "Band walks + ankle circles", description: "Mini band above knees: 10 lateral steps each way ×2. Then 10 ankle circles each direction, each foot.", minutes: 2 },
  { block: "ACTIVATE", level: 1, name: "Two-ball pound", description: "Two balls: pound together 30 sec, alternate 30 sec, low (below knee) 30 sec. Eyes up the whole time.", minutes: 2 },
  { block: "ACTIVATE", level: 1, name: "Figure-8 walks", description: "Walk the driveway/hall wrapping the ball around your legs in a figure-8. There and back ×2. Then reverse direction.", minutes: 2 },
  { block: "ACTIVATE", level: 1, name: "Jump-stop / pivot series", description: "Jog 3 steps → jump stop → front pivot ×2, reverse pivot ×2. 6 reps each pivot foot. Stay low on the pivot.", minutes: 2 },
  { block: "ACTIVATE", level: 1, name: "Hip openers + A-skips", description: "10 leg swings each direction each leg, then A-skips 2 × 15 yards. Tall posture, quick ground contact.", minutes: 2 },
  { block: "ACTIVATE", level: 1, name: "Ball slaps + fingertip taps", description: "Slap the ball hard 20×, then fingertip taps overhead 30 sec, at the waist 30 sec, at the ankles 30 sec.", minutes: 2 },

  // ───────── HANDLE ─────────
  // L1 — control
  { block: "HANDLE", level: 1, name: "Stationary pound series", description: "Right hand 30 sec, left 30 sec, crossover 30 sec, between legs 30 sec, behind back 30 sec. Hard dribbles, eyes up.", minutes: 3 },
  { block: "HANDLE", level: 1, name: "Cone crossover attack", description: "3 cones (or shoes) 5 ft apart. Crossover at each cone, sprint through the last. 6 trips, alternate start hand.", minutes: 3 },
  { block: "HANDLE", level: 1, name: "30-sec pressure rounds", description: "Dribble 30 sec inside a 6×6 ft box, ball below the knee. 3 rounds, 20 sec rest. If it gets away, that's a rep lost.", minutes: 3 },
  { block: "HANDLE", level: 1, name: "Weak-hand wall taps", description: "Fingertip taps on a wall above your head, weak hand only, 30 sec ×3. Then 30 sec weak-hand pound.", minutes: 3 },
  // L2 — two balls + change of direction
  { block: "HANDLE", level: 2, name: "Two-ball stationary", description: "Same-time pound 30s, alternating 30s, one high one low 30s, crossover both 30s. Ball never above the waist.", minutes: 3 },
  { block: "HANDLE", level: 2, name: "In-and-out to cross", description: "In-and-out then crossover at each of 3 cones. 8 trips. Sell the in-and-out with the shoulder, not just the hand.", minutes: 3 },
  { block: "HANDLE", level: 2, name: "Retreat dribble + re-attack", description: "Attack 2 steps, two hard retreat dribbles, crossover, re-attack. 10 reps each side. Eyes on an imaginary rim.", minutes: 3 },
  { block: "HANDLE", level: 2, name: "Tennis-ball toss dribble", description: "Dribble with one hand while tossing and catching a tennis ball with the other. 45 sec each hand ×2.", minutes: 3 },
  // L3 — combos under time
  { block: "HANDLE", level: 3, name: "Combo ladder", description: "Cross → between → behind, continuous for 45 sec. Then reverse the order 45 sec. 2 rounds. Count clean cycles.", minutes: 3 },
  { block: "HANDLE", level: 3, name: "Cone snake, 5 cones", description: "5 cones in a line 4 ft apart. Alternate crossover / between the legs at each cone, both directions. 6 trips at game speed.", minutes: 3 },
  { block: "HANDLE", level: 3, name: "Hesitation series", description: "Attack, hard hesitation (ball pauses, eyes up, body sells 'shot'), then explode. 8 each hand. Then hesi-cross 8 each hand.", minutes: 3 },
  { block: "HANDLE", level: 3, name: "Two-ball moving", description: "Two balls, walk then jog the length of the space: same-time, alternating, then crossover. 3 trips each.", minutes: 3 },
  // L4 — pressure and pace
  { block: "HANDLE", level: 4, name: "Wall pressure dribble", description: "Dribble 3 ft from a wall with your back to it, imaginary defender at your hip. Protect with off arm, change hands every 3 dribbles. 3 × 45 sec.", minutes: 3 },
  { block: "HANDLE", level: 4, name: "Change-of-pace lines", description: "Slow-slow-FAST-slow across the space. Every 'FAST' is a real burst. 8 trips, alternate the move that starts the burst (cross, between, behind).", minutes: 3 },
  { block: "HANDLE", level: 4, name: "Reaction combos", description: "Have someone call (or use a random-call app) 'cross / between / behind / spin'. React instantly, 60 sec × 3 rounds.", minutes: 3 },
  { block: "HANDLE", level: 4, name: "Two-ball combos", description: "Two balls: cross both, between with one while pounding the other, alternate. 45 sec each ×2. Count clean reps.", minutes: 3 },
  // L5 — reads
  { block: "HANDLE", level: 5, name: "Chair defender reads", description: "Chair = defender. Attack, read its 'hip' (call it out loud), counter the other way with the right move. 12 reps, vary the move each time.", minutes: 4 },
  { block: "HANDLE", level: 5, name: "Snake dribble + pull back", description: "Snake around 3 cones, then pull-back at the last cone into a step-back footwork rep. 8 each direction.", minutes: 3 },
  { block: "HANDLE", level: 5, name: "Off-hand only session", description: "Everything with the weak hand: pound, cross to weak, between to weak, attack lines. 3 × 60 sec, no strong-hand touches.", minutes: 3 },
  { block: "HANDLE", level: 5, name: "Fatigue handle", description: "10 burpees → 45 sec combo ladder → 10 burpees → 45 sec cone snake. Handle has to hold when your legs are gone.", minutes: 4 },
  // L6 — game
  { block: "HANDLE", level: 6, name: "Live 1-on-1 handle (or shadow)", description: "With a partner: 1-on-1 from the top, 3 dribbles max to score. No partner: shadow the same reads at full speed, 12 reps, calling the read out loud.", minutes: 4 },
  { block: "HANDLE", level: 6, name: "Pick-and-roll handle series", description: "Chair = screener. Reject, use, split, re-use. 4 reps each, each side. Snake dribble on the use.", minutes: 4 },
  { block: "HANDLE", level: 6, name: "Two-ball at full speed with reads", description: "Two-ball combos at a sprint, react to a caller. 3 × 45 sec. If you can hold a conversation you're not going hard enough.", minutes: 3 },
  { block: "HANDLE", level: 6, name: "Transition push", description: "Sprint dribble the full space, change of direction at half, finish footwork at the end. 10 reps, alternate hands. Time yourself.", minutes: 3 },

  // ───────── FINISH / FOOTWORK ─────────
  // L1 — layups and pivots
  { block: "FINISH", level: 1, name: "Mikan drill", description: "Alternate right/left layups under the rim, ball never touches the ground. 2 × 60 sec. Count makes.", needsHoop: true, noHoopName: "Layup footwork lines", noHoopDescription: "Mark a spot as the rim. Two-step layup footwork right (R-L, jump off left) ×10, left ×10. Full extension, ball high and away from the 'defender'.", minutes: 3 },
  { block: "FINISH", level: 1, name: "One-dribble finish, both sides", description: "Start at the elbow, one dribble to the rim, finish. 8 each side, then 8 each side off the opposite foot.", needsHoop: true, noHoopName: "Jab-rip-go", noHoopDescription: "Triple threat vs. a chair: jab, rip through low, explode two dribbles past the chair. 10 each side.", minutes: 3 },
  { block: "FINISH", level: 1, name: "Reverse Mikan", description: "Mikan but finish on the far side of the rim (reverse). 2 × 45 sec. Use the rim to protect the ball.", needsHoop: true, noHoopName: "Drop-step + spin footwork", noHoopDescription: "Back to the 'basket', catch, drop step baseline ×10 each side, then spin ×10 each side. Stay low, ball chinned.", minutes: 3 },
  { block: "FINISH", level: 1, name: "Inside-hand finish", description: "Drive right, finish with the LEFT (inside) hand; drive left, finish RIGHT. 8 each side. Keeps the ball away from the help.", needsHoop: true, noHoopName: "Euro-step lines", noHoopDescription: "Two cones. Drive, plant outside foot at cone 1, step past cone 2 the other way. 8 each direction, ball tucked.", minutes: 3 },
  // L2 — footwork variety
  { block: "FINISH", level: 2, name: "Euro-step finishes", description: "Drive, plant outside the chair, step across, finish opposite. 8 each side. Ball stays tucked through the second step.", needsHoop: true, noHoopName: "Euro-step at speed", noHoopDescription: "Same footwork at a sprint with a chair as the help defender. 10 each side. Land balanced.", minutes: 3 },
  { block: "FINISH", level: 2, name: "Pro-hop finishes", description: "Drive, one-two hop off both feet past the chair, finish. 8 each side. Absorb contact with the hop.", needsHoop: true, noHoopName: "Pro-hop footwork", noHoopDescription: "Two-foot hop past the chair, land balanced, rise with the ball high. 10 each side.", minutes: 3 },
  { block: "FINISH", level: 2, name: "Reverse layups from the wing", description: "Drive baseline from the wing, finish reverse on the other side. 8 each side. Eyes on the far square.", needsHoop: true, noHoopName: "Baseline drive footwork", noHoopDescription: "Wing to 'baseline' drive, two steps, reverse finish motion. 10 each side.", minutes: 3 },
  { block: "FINISH", level: 2, name: "Floater form", description: "One dribble from the free-throw line, soft one-hand floater off one foot then two feet. 10 each. Soft is the goal, not makes.", needsHoop: true, noHoopName: "Floater release to a wall", noHoopDescription: "One-hand floater release to a mark high on a wall, off one foot ×10, two feet ×10. High arc, soft hand.", minutes: 3 },
  // L3 — contact and counters
  { block: "FINISH", level: 3, name: "Contact finishes (pad or partner)", description: "Partner bumps you with a pad on the drive (or you drive into a bag/chair). Finish through contact. 8 each side.", needsHoop: true, noHoopName: "Contact absorption reps", noHoopDescription: "Drive into a cushion/chair, absorb with the shoulder, keep the ball high with two hands. 10 each side.", minutes: 3 },
  { block: "FINISH", level: 3, name: "Spin move finish", description: "Drive, spin off the chair, finish inside hand. 8 each side. Keep the ball tight on the spin.", needsHoop: true, noHoopName: "Spin footwork series", noHoopDescription: "Spin off the chair both directions ×10 each. Plant, chin the ball, spin, land balanced.", minutes: 3 },
  { block: "FINISH", level: 3, name: "Up-and-under", description: "Catch on the block, shot fake, step through, finish. 8 each side. Fake has to be a real fake — eyes go up.", needsHoop: true, noHoopName: "Shot-fake step-through footwork", noHoopDescription: "Catch, fake, step through vs. the chair, 10 each side. Pivot foot stays planted.", minutes: 3 },
  { block: "FINISH", level: 3, name: "Same-foot (wrong-foot) finishes", description: "Finish off the same-side foot (right hand, right foot). 8 each side. Quicker release than a defender expects.", needsHoop: true, noHoopName: "Wrong-foot takeoff reps", noHoopDescription: "Two dribbles, take off same-side foot, ball high. 10 each side.", minutes: 3 },
  // L4 — speed + decision
  { block: "FINISH", level: 4, name: "Finishing series, 60 sec", description: "Continuous: right layup, left layup, right reverse, left reverse, floater — repeat. 60 sec, count makes. 2 rounds.", needsHoop: true, noHoopName: "Finishing footwork circuit", noHoopDescription: "Same 5-move sequence as footwork only, continuous 60 sec × 2. Sharp, balanced landings.", minutes: 3 },
  { block: "FINISH", level: 4, name: "Read the help (chair moves)", description: "Partner moves the chair last-second to one side; you finish away from it (Euro, pro-hop, reverse). 10 reps. No partner: decide before the last dribble and commit.", needsHoop: true, noHoopName: "Late-read finishing footwork", noHoopDescription: "Same reads as footwork, partner or self-called at the last step. 12 reps.", minutes: 4 },
  { block: "FINISH", level: 4, name: "Off-two-feet power finish", description: "Drive, jump stop under the rim, finish strong with two hands or high off the glass. 8 each side.", needsHoop: true, noHoopName: "Jump-stop power reps", noHoopDescription: "Sprint, jump stop, rise with the ball above the head, 10 reps. Landing quiet.", minutes: 3 },
  { block: "FINISH", level: 4, name: "Floater off the dribble", description: "Full speed drive, floater from 8–10 ft off one foot. 10 each side. Track makes.", needsHoop: true, noHoopName: "Floater release at speed", noHoopDescription: "Drive, one-foot floater release to a high wall mark, 10 each side.", minutes: 3 },
  // L5 — game shapes
  { block: "FINISH", level: 5, name: "Transition finishes vs. trailer", description: "Sprint from half, finish with a chair (or partner) trailing. Choose the finish that protects from behind. 10 reps.", needsHoop: true, noHoopName: "Transition footwork at speed", noHoopDescription: "Sprint, gather, finish footwork with the ball high and away, 10 reps.", minutes: 3 },
  { block: "FINISH", level: 5, name: "Post finishes series", description: "Back to the basket: drop step, jump hook, up-and-under, turnaround. 5 each, each side.", needsHoop: true, noHoopName: "Post footwork series", noHoopDescription: "Same four moves as footwork vs. a chair, 6 each side.", minutes: 4 },
  { block: "FINISH", level: 5, name: "Fatigue finishes", description: "5 sprints, then 45 sec of alternating finishes. 3 rounds. Finishing has to hold when you're tired.", needsHoop: true, noHoopName: "Fatigue footwork", noHoopDescription: "5 sprints then 45 sec finishing footwork circuit, 3 rounds.", minutes: 4 },
  { block: "FINISH", level: 5, name: "Runner off the glass", description: "Drive at an angle, high runner off the glass over a raised-hands partner or chair. 8 each side.", needsHoop: true, noHoopName: "Runner release", noHoopDescription: "Angle drive, one-foot high release to a wall mark, 10 each side.", minutes: 3 },
  // L6 — live
  { block: "FINISH", level: 6, name: "Live finishing 1-on-1 from the wing", description: "Partner defends from the wing, 2 dribbles max, finish. 10 reps. No partner: full-speed shadow with a called read.", needsHoop: true, noHoopName: "Shadow finishing at game speed", noHoopDescription: "Full-speed reads with called defender positions, 12 reps.", minutes: 4 },
  { block: "FINISH", level: 6, name: "Pick-and-roll finishing", description: "Use a chair screen, turn the corner, finish vs. a drop (floater) or a switch (drive). 6 each, each side.", needsHoop: true, noHoopName: "PnR finishing footwork", noHoopDescription: "Chair screen, turn the corner, floater or drive footwork, 8 each side.", minutes: 4 },
  { block: "FINISH", level: 6, name: "Finishing series, 60 sec — all moves", description: "Every finish you own, continuous, 60 sec × 2. Log makes; this is a benchmark preview.", needsHoop: true, noHoopName: "Full footwork circuit", noHoopDescription: "All finishing footwork, continuous 60 sec × 2.", minutes: 3 },
  { block: "FINISH", level: 6, name: "Contested layup lines", description: "Partner contests every rep from a step behind. 10 each side. Absorb, finish high.", needsHoop: true, noHoopName: "Contested footwork", noHoopDescription: "Partner or chair contact on the gather, finish motion high, 10 each side.", minutes: 3 },

  // ───────── SHOOT ─────────
  // L1 — form
  { block: "SHOOT", level: 1, name: "Form shooting, 1 ft", description: "One hand, 1 ft from the rim. 20 makes. Elbow under, snap the wrist, hold the follow-through.", needsHoop: true, noHoopName: "Wall form shooting", noHoopDescription: "3 ft from a wall (or lying on your back). One-hand shoot to yourself: 3 × 15. Spin straight back, ball returns to the same hand.", minutes: 4 },
  { block: "SHOOT", level: 1, name: "Elbow-to-elbow", description: "Catch at one elbow, shoot, run to the other elbow, catch (or self-toss), shoot. 2 × 10 shots. Count makes.", needsHoop: true, noHoopName: "Lift-and-hold on a line", noHoopDescription: "Feet on a line, catch a self-toss, shooting motion with full follow-through, hold 2 sec. 2 × 12. Feet land the same every time.", minutes: 4 },
  { block: "SHOOT", level: 1, name: "Spot shooting, 5 spots", description: "Baseline, wing, top, wing, baseline (mid-range or 3 by grade). 5 shots each. Count makes out of 25.", needsHoop: true, noHoopName: "One-hand release holds", noHoopDescription: "Ball in shooting hand only, guide hand off. Shoot straight up 3 ft and catch. 3 × 15. Perfect rotation every rep.", minutes: 5 },
  { block: "SHOOT", level: 1, name: "Free throws with routine", description: "10 free throws. Same routine every time: breathe, bounce, look, shoot. Count makes.", needsHoop: true, noHoopName: "Routine reps", noHoopDescription: "Run your free-throw routine to an imaginary rim ×10, full follow-through hold.", minutes: 3 },
  // L2 — footwork into the shot
  { block: "SHOOT", level: 2, name: "Form shooting, 3 spots close", description: "One hand then two hands from 3 ft, front and both sides. 10 makes each spot. Same release every time.", needsHoop: true, noHoopName: "Two-hand wall form", noHoopDescription: "Add the guide hand, shoot to a wall mark 3 × 15. Guide hand comes off before release.", minutes: 4 },
  { block: "SHOOT", level: 2, name: "1-2 step catch-and-shoot", description: "Self-toss or partner pass, inside foot first, 1-2 step into the shot. 5 spots × 4 shots. Count makes.", needsHoop: true, noHoopName: "1-2 step footwork holds", noHoopDescription: "Toss, 1-2 step, full shooting motion, hold. 5 spots × 5 reps. Land where you took off.", minutes: 4 },
  { block: "SHOOT", level: 2, name: "Hop catch-and-shoot", description: "Same as 1-2 but with a hop into the catch. 5 spots × 4. Feel which one is faster for you.", needsHoop: true, noHoopName: "Hop footwork holds", noHoopDescription: "Toss, hop, shoot motion, hold. 5 spots × 5 reps.", minutes: 4 },
  { block: "SHOOT", level: 2, name: "One-dribble pull-ups", description: "From the wing, one dribble left or right, pull-up. 8 each direction. Balanced on the rise.", needsHoop: true, noHoopName: "One-dribble pull-up footwork", noHoopDescription: "One dribble, plant, rise with the shooting motion, hold. 10 each direction.", minutes: 4 },
  { block: "SHOOT", level: 2, name: "Spot shooting under time", description: "5 spots, 2 min, as many good shots as possible. Count makes. Quality over speed.", needsHoop: true, noHoopName: "Release speed reps", noHoopDescription: "Catch-and-release to a wall mark, 30 sec × 3, count perfect reps.", minutes: 5 },
  // L3 — off the move
  { block: "SHOOT", level: 3, name: "Curl / fade off a chair screen", description: "Chair on the wing. Curl into a shot ×6 each side, fade into a shot ×6 each side. Feet set on the catch.", needsHoop: true, noHoopName: "Curl / fade footwork", noHoopDescription: "Same routes around the chair, catch a self-toss, shooting motion, hold. 8 each.", minutes: 4 },
  { block: "SHOOT", level: 3, name: "Relocation shooting", description: "Shoot, sprint to a new spot, catch, shoot. 12 shots continuous. Count makes.", needsHoop: true, noHoopName: "Relocate + release", noHoopDescription: "Release to a wall mark, sprint to a new spot, release again. 12 reps.", minutes: 4 },
  { block: "SHOOT", level: 3, name: "Step-back series", description: "One dribble step-back both directions from the wing and top. 6 each. Land balanced, shoulders square.", needsHoop: true, noHoopName: "Step-back footwork", noHoopDescription: "Dribble, push off, land square, shooting motion. 8 each direction.", minutes: 4 },
  { block: "SHOOT", level: 3, name: "10-minute shooting (short version)", description: "5 spots, continuous, 5 min. Count makes — this is your JLaw-style volume number.", needsHoop: true, noHoopName: "5-min form volume", noHoopDescription: "Continuous wall form shooting 5 min, count perfect reps.", minutes: 5 },
  // L4 — pressure and range
  { block: "SHOOT", level: 4, name: "Hand-in-face shooting", description: "Partner (or broom) contests the release. 5 spots × 4. Same release, don't drift.", needsHoop: true, noHoopName: "Contested release holds", noHoopDescription: "Partner/broom in your face, catch, release to a wall mark, hold. 15 reps.", minutes: 4 },
  { block: "SHOOT", level: 4, name: "Range ladder", description: "Make 3 in a row from 3 ft, step back 2 ft, repeat until you miss twice in a row. Log the distance.", needsHoop: true, noHoopName: "Power form reps", noHoopDescription: "Wall shooting from 8 ft, 10 ft, 12 ft with legs driving the shot. 10 each.", minutes: 5 },
  { block: "SHOOT", level: 4, name: "Pull-ups off two dribbles", description: "Cross / between / behind into a two-dribble pull-up, both directions, 3 spots. 12 shots.", needsHoop: true, noHoopName: "Two-dribble pull-up footwork", noHoopDescription: "Move into two dribbles, plant, rise, hold. 12 reps.", minutes: 4 },
  { block: "SHOOT", level: 4, name: "Free throws, pressure", description: "10 FTs. Every miss = 5 push-ups then shoot again. Count makes.", needsHoop: true, noHoopName: "Routine under fatigue", noHoopDescription: "10 burpees, then 10 routine reps with full follow-through. Breathe.", minutes: 3 },
  // L5 — game reps
  { block: "SHOOT", level: 5, name: "Game-speed catch-and-shoot, 3 spots × 10", description: "Partner passes (or self-toss hard), shot off the catch at game speed. 30 shots, count makes.", needsHoop: true, noHoopName: "Game-speed catch + release", noHoopDescription: "Hard self-toss, catch, release to a wall mark, 30 reps.", minutes: 5 },
  { block: "SHOOT", level: 5, name: "Shots off ball screens", description: "Chair screen at the top: reject into pull-up, use into pull-up, snake into a mid-range. 5 each, each side.", needsHoop: true, noHoopName: "PnR shooting footwork", noHoopDescription: "Same three routes with a shooting motion and hold, 6 each side.", minutes: 4 },
  { block: "SHOOT", level: 5, name: "Fatigue shooting", description: "Full-court sprint (or 3 shuttles), then 5 shots from a spot. 4 rounds. Count makes.", needsHoop: true, noHoopName: "Fatigue release", noHoopDescription: "3 shuttles then 10 wall form reps, 4 rounds. Legs still drive the shot.", minutes: 5 },
  { block: "SHOOT", level: 5, name: "Make 7 of 10 or restart", description: "One spot. Make 7 of 10 to move on. 5 spots. Log how many restarts.", needsHoop: true, noHoopName: "10 perfect reps or restart", noHoopDescription: "10 perfect wall form reps in a row per 'spot', restart on a bad one. 5 spots.", minutes: 5 },
  // L6 — closer
  { block: "SHOOT", level: 6, name: "10-minute shooting", description: "5 spots, continuous, 10 min, partner rebounds if you have one. Count makes. Log it — this is your before/after number.", needsHoop: true, noHoopName: "10-min form volume", noHoopDescription: "Continuous wall form shooting 10 min, count perfect reps.", minutes: 10 },
  { block: "SHOOT", level: 6, name: "Late-clock shots", description: "Partner counts down from 3; you have to create and get a shot off. 12 reps, alternate move. No partner: self count.", needsHoop: true, noHoopName: "3-count create + release", noHoopDescription: "Count down 3, create separation with a move, release to a wall mark. 12 reps.", minutes: 4 },
  { block: "SHOOT", level: 6, name: "Contested pull-ups", description: "Partner contests every pull-up off 1–2 dribbles. 5 spots × 4. Count makes.", needsHoop: true, noHoopName: "Contested pull-up footwork", noHoopDescription: "Partner contests the rise, 15 reps, hold the finish.", minutes: 4 },
  { block: "SHOOT", level: 6, name: "Free throws, 20 with consequences", description: "20 FTs. Miss two in a row = 3 sprints. Count makes.", needsHoop: true, noHoopName: "Routine, 20 reps", noHoopDescription: "20 routine reps, full follow-through, eyes on a target.", minutes: 4 },

  // ───────── ENGINE (no levels) ─────────
  { block: "ENGINE", level: 1, name: "Defensive slides, 20/20", description: "20 sec of low slides, 20 sec rest × 4. Hands active, no crossing feet.", minutes: 3 },
  { block: "ENGINE", level: 1, name: "Bodyweight strength circuit", description: "Squats ×15, push-ups ×10, reverse lunges ×8 each, plank 30 sec. 2 rounds.", minutes: 4 },
  { block: "ENGINE", level: 1, name: "Pogo hops + single-leg balance", description: "Pogo hops 3 × 20 (stiff ankles, quick). Then single-leg balance 30 sec each leg, eyes closed if you can.", minutes: 3 },
  { block: "ENGINE", level: 1, name: "5-10-5 practice", description: "Cones 5 yards apart. 4 reps of the 5-10-5 shuttle with full rest. Touch the line with your hand.", minutes: 3 },
  { block: "ENGINE", level: 1, name: "Closeout + slide + sprint", description: "Sprint 5 yards, chop into a closeout, slide 3, sprint back. 6 reps, 30 sec rest.", minutes: 3 },
  { block: "ENGINE", level: 1, name: "Band-resisted first step", description: "Band around waist held by partner or anchored: 6 explosive first steps each side. No band: 8 broad jumps, stick the landing.", minutes: 3 },
  { block: "ENGINE", level: 1, name: "Core: dead bugs + side planks", description: "Dead bugs 2 × 10 each side, side plank 30 sec each side × 2.", minutes: 3 },
  { block: "ENGINE", level: 1, name: "Split squats + calf raises", description: "Split squats 2 × 10 each leg, single-leg calf raises 2 × 15 each. Slow down, fast up.", minutes: 4 },
];
